---
- include: archlinux.yml
- include: darwin.yml
- hosts: localhost
  connection: local
  sudo: no
  vars_files:
    - vars/mkdir.yml
    - vars/go_packages.yml
  vars:
    ansible_python_interpreter: python2
  tasks:
    - include: tasks/common.yml
    - include: tasks/go-get.yml
