---
    - name: mkdir
      file: path={{ item }} state=directory
      with_items: mkdir_items

    - name: neobundle get status
      git: repo=git://github.com/Shougo/neobundle.vim.git dest=~/.vim/bundle/neobundle.vim

    - name: install dotfiles
      git: repo=https://github.com/flaflasun/dotfiles.git dest=~/dotfiles

    - name: make symlinks of dotfiles
      file: src={{ item }} dest=~/.{{ item | basename }} state=link force=yes
      with_fileglob: ~/dotfiles/*
      when: item | basename != "README.md"
