---
    - name: mkdir
      file: path={{ item }} state=directory
      with_items: mkdir_items

    - name: neobundle get status
      register: neobundle
      stat: path=~/.vim/bundle/neobundle.vim
    - name: install neobundle
      command: git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
      when: neobundle.stat.exists == false

    - name: dotfiles get status
      register: dotfiles
      stat: path=~/dotfiles
    - name: install dotfiles
      command: git clone git://github.com/flaflasun/dotfiles ~/dotfiles
      when: dotfiles.stat.exists == false

    - name: make symlinks of dotfiels
      file: src={{ item }} dest=~/.{{ item | basename }} state=link force=yes
      with_fileglob:
        - ~/dotfiles/*
