---
    - name: mkdir vim backup dir
      file: path=~/.vim/tmp/backup state=directory

    - name: mkdir vim swap dir
      file: path=~/.vim/tmp/swap state=directory

    - name: mkdir vim undo dir
      file: path=~/.vim/tmp/undo state=directory

    - name: mkdir vim-neobundle dir
      file: path=~/.vim/bundle state=directory

    - name: neobundle get status
      register: neobundle
      stat: path=~/.vim/bundle/neobundle.vim
    - name: install neobundle
      command: git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
      when: neobundle.stat.exists == false

    - name: dotfiles get status
      register: dotfiles
      stat: path=~/dotfiles
    - name: install dotfiles
      command: git clone git://github.com/flaflasun/dotfiles ~/dotfiles
      when: dotfiles.stat.exists == false
