---
    - name: check go packages status
      command: go list {{ item }}
      register: golist_result
      failed_when: golist_result.rc not in [0, 1]
      changed_when: golist_result.rc not in [0, 1]
      with_items: go_packages
    - name: install go packages
      command: go get {{ item.item }}
      when: item.rc == 1
      with_items: golist_result.results
